# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

cran: https://cran.rstudio.com/
env:
  global:
    - CRAN_REPO=https://cran.rstudio.com
jobs:
  include:
  - os: linux
    dist: bionic
    r: oldrel
  - os: linux
    dist: bionic
    r: release
    after_success:
      - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
      - Rscript -e 'lintr::lint_package()'
    r_github_packages:
      - jimhester/lintr
  - os: linux
    dist: bionic
    r: devel
  - os: osx
    osx_image: xcode9.4
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
